[package]
name = "fights-srv"
version = "0.1.0"
edition = "2021"

[lib]
name = "fights_srv"
crate-type = ["lib"]

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.5.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
